### PR TITLE
made a bunch of QoL changes i guess, full list of changes below, i mightve been 18 commits behind tho so this might conflict a bit on some parts

### PR DESCRIPTION
**Pull request by notmynamex**
- coord.py: added a comment

- economy.py: corrected spelling mistake

- scoresaber.py: added some consistency with the oopsie woopsies

- text.py: added funny secret DG command, similar to the NOPE command

- tourn_app.py: removed an unnecessary indent

- user.py: hilarious

- work.py: added funny comment, very much needed

- README.md: corrrected a spelling mistake

- requirements.txt: bumped requests from 2.23.0 to 2.25.0, bumped discord.py from 1.7.0 to 1.7.3, bumped firebase_admin from 4.5.1 to 5.0.1, bumped discord-ext-alternatives from 2020.10.11 to 2021.4.13, bumped DiscordUtils from 1.2.6 to 1.3.4, bumped NHentai-API from 0.0.15 to 0.0.16, bumped jishaku from 1.20.0.220 to 2.0.0, bumped python-dotenv from 0.15.0 to 0.18.0

- runtime.txt: bumped python version from 3.8.9 to 3.9.6

- scuffed_bot.py: added watch statuses, only a few though

### CODE REVIEW

**Comment by Taffeeko** [comment]
I hate you

**Comment by notmynamex** [comment]
why do you hate me, im just trying to help improve your bot?

**Comment by Taffeeko** [comment]
You are literally a contributor why even bother doing it like this

**Comment by notmynamex** [comment]
i dont have write access

**Comment by Taffeeko** [comment]
good :tf:

**Comment by notmynamex** [comment]
now merge please, this was a lot of work

**Comment by Taffeeko** [comment]
No, I'm going to play beat saber first B)

**Comment by notmynamex** [comment]
i am in despair

**Comment by thijnmens** [comment]
bada biem bada boem i have no idea what this does but here we go

**Comment by notmynamex** [comment]
i literally listed what i changed wdym you have no idea

**Pull request merged**
