### PR TITLE
Revert "made a bunch of QoL changes i guess, full list of changes below, i mightve been 18 commits behind tho so this might conflict a bit on some parts"

### PR DESCRIPTION
**Pull request by Taffeeko**
I simply do not like some of the changes

### CODE REVIEW

**Comment by notmynamex** [comment]
which ones

**Comment by Taffeeko** [comment]
well I want to fix them but I cannot figure out how >:(((

**Comment by notmynamex** [comment]
fix what

**Comment by notmynamex** [comment]
no watching status?

**Comment by Taffeeko** [comment]
I'll do something for that later

**Comment by Taffeeko** [comment]
Scuffed bot really needs a rewrite lmao

**Comment by notmynamex** [comment]
tell me if i can do sth to help if you rewrite

**Comment by Taffeeko** [comment]
> tell me if i can do sth to help if you rewrite

learn PEP8 :tf:

**Comment by notmynamex** [comment]
agony

**Pull request merged**
