### PR TITLE
fixed scoresaber cog

### PR DESCRIPTION
**Pull request by notmynamex**
i hope this works
also suck my cock spam your code sucks

### CODE REVIEW

**Comment by Taffeeko** [comment]
Going to archive this hell hole eventually, you won't have to see my shit code anymore

**Comment by notmynamex** [comment]
but funny bot, you cant just kill it

**Comment by Taffeeko** [comment]
Oh wait this isn't Sirbot, never mind :tf:

**Comment by notmynamex** [comment]
smartass

**Pull request merged**
